load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pinocchio",
    hdrs = glob([
        "*.hpp",
    ]),
    visibility = [
        "//examples:__subpackages__",
        "//tests:__subpackages__",
        "//pinocchio:__subpackages__",        
    ],
    deps = [ 
    ],
)